require("nvim-treesitter").setup({
	highlight = { enable = true },
	indent = { enable = true },
})

-- nvim-treesitter-textobjects
vim.keymap.set({ "x", "o" }, "af", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@function.outer", "textobjects")
end, { desc = "Around [f]unction (outer)" })
vim.keymap.set({ "x", "o" }, "if", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@function.inner", "textobjects")
end, { desc = "Inside [f]unction (inner)" })
vim.keymap.set({ "x", "o" }, "ac", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@class.outer", "textobjects")
end, { desc = "Around [c]lass (outer)" })
vim.keymap.set({ "x", "o" }, "ic", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@class.inner", "textobjects")
end, { desc = "Inside [c]lass (inner)" })
vim.keymap.set({ "x", "o" }, "as", function()
	require("nvim-treesitter-textobjects.select").select_textobject("@local.scope", "locals")
end, { desc = "Around [s]cope" })

vim.keymap.set("n", "<leader>a", function()
	require("nvim-treesitter-textobjects.swap").swap_next("@parameter.inner")
end, { desc = "Swap next [a]rgument" })
vim.keymap.set("n", "<leader>A", function()
	require("nvim-treesitter-textobjects.swap").swap_previous("@parameter.outer")
end, { desc = "Swap previous [A]rgument" })

vim.keymap.set({ "n", "x", "o" }, "]m", function()
	require("nvim-treesitter-textobjects.move").goto_next_start("@function.outer", "textobjects")
end, { desc = "Next function [m] (start)" })
vim.keymap.set({ "n", "x", "o" }, "]M", function()
	require("nvim-treesitter-textobjects.move").goto_next_end("@function.outer", "textobjects")
end, { desc = "Next function [M] (end)" })
vim.keymap.set({ "n", "x", "o" }, "]p", function()
	require("nvim-treesitter-textobjects.move").goto_next_start("@parameter.outer", "textobjects")
end, { desc = "Next [p]arameter (start)" })
vim.keymap.set({ "n", "x", "o" }, "]P", function()
	require("nvim-treesitter-textobjects.move").goto_next_end("@parameter.outer", "textobjects")
end, { desc = "Next [P]arameter (end)" })
vim.keymap.set({ "n", "x", "o" }, "[m", function()
	require("nvim-treesitter-textobjects.move").goto_previous_start("@function.outer", "textobjects")
end, { desc = "Previous function [m] (start)" })
vim.keymap.set({ "n", "x", "o" }, "[M", function()
	require("nvim-treesitter-textobjects.move").goto_previous_end("@function.outer", "textobjects")
end, { desc = "Previous function [M] (end)" })
vim.keymap.set({ "n", "x", "o" }, "[p", function()
	require("nvim-treesitter-textobjects.move").goto_previous_start("@parameter.outer", "textobjects")
end, { desc = "Previous [p]arameter (start)" })
vim.keymap.set({ "n", "x", "o" }, "[P", function()
	require("nvim-treesitter-textobjects.move").goto_previous_end("@parameter.outer", "textobjects")
end, { desc = "Previous [P]arameter (end)" })

require("ts_context_commentstring").setup()
